server:
  port: 8092
spring:
  application:
    name: fitness-workload-service
  profiles:
    active: "helper"
  config:
    import: [optional:configserver:http://root:s3cr3t@localhost:8888, classpath:secret.yml]

feign:
  circuitbreaker:
    enabled: true
